import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-900">
        <Navbar />
        <main className="container mx-auto p-4 min-h-screen">
          {children}
        </main>
        
        {/* Simple Footer */}
        <footer className="bg-gray-800 text-white text-center p-4 mt-8">
          <p>© 2026 Makaut Hub - Built for Students</p>
        </footer>
      </body>
    </html>
  );
}
